package com.web.spring.model;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
	 * @mbg.generated  Fri Jul 30 22:07:16 ICT 2021
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.createdby
	 * @mbg.generated  Fri Jul 30 22:07:16 ICT 2021
	 */
	private String createdby;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.createddate
	 * @mbg.generated  Fri Jul 30 22:07:16 ICT 2021
	 */
	private Date createddate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.modifiedby
	 * @mbg.generated  Fri Jul 30 22:07:16 ICT 2021
	 */
	private String modifiedby;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.modifieddate
	 * @mbg.generated  Fri Jul 30 22:07:16 ICT 2021
	 */
	private Date modifieddate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.fullname
	 * @mbg.generated  Fri Jul 30 22:07:16 ICT 2021
	 */
	private String fullname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
	 * @mbg.generated  Fri Jul 30 22:07:16 ICT 2021
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.status
	 * @mbg.generated  Fri Jul 30 22:07:16 ICT 2021
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.username
	 * @mbg.generated  Fri Jul 30 22:07:16 ICT 2021
	 */
	private String username;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
	 * @return  the value of user.id
	 * @mbg.generated  Fri Jul 30 22:07:16 ICT 2021
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
	 * @param id  the value for user.id
	 * @mbg.generated  Fri Jul 30 22:07:16 ICT 2021
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.createdby
	 * @return  the value of user.createdby
	 * @mbg.generated  Fri Jul 30 22:07:16 ICT 2021
	 */
	public String getCreatedby() {
		return createdby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.createdby
	 * @param createdby  the value for user.createdby
	 * @mbg.generated  Fri Jul 30 22:07:16 ICT 2021
	 */
	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.createddate
	 * @return  the value of user.createddate
	 * @mbg.generated  Fri Jul 30 22:07:16 ICT 2021
	 */
	public Date getCreateddate() {
		return createddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.createddate
	 * @param createddate  the value for user.createddate
	 * @mbg.generated  Fri Jul 30 22:07:16 ICT 2021
	 */
	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.modifiedby
	 * @return  the value of user.modifiedby
	 * @mbg.generated  Fri Jul 30 22:07:16 ICT 2021
	 */
	public String getModifiedby() {
		return modifiedby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.modifiedby
	 * @param modifiedby  the value for user.modifiedby
	 * @mbg.generated  Fri Jul 30 22:07:16 ICT 2021
	 */
	public void setModifiedby(String modifiedby) {
		this.modifiedby = modifiedby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.modifieddate
	 * @return  the value of user.modifieddate
	 * @mbg.generated  Fri Jul 30 22:07:16 ICT 2021
	 */
	public Date getModifieddate() {
		return modifieddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.modifieddate
	 * @param modifieddate  the value for user.modifieddate
	 * @mbg.generated  Fri Jul 30 22:07:16 ICT 2021
	 */
	public void setModifieddate(Date modifieddate) {
		this.modifieddate = modifieddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.fullname
	 * @return  the value of user.fullname
	 * @mbg.generated  Fri Jul 30 22:07:16 ICT 2021
	 */
	public String getFullname() {
		return fullname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.fullname
	 * @param fullname  the value for user.fullname
	 * @mbg.generated  Fri Jul 30 22:07:16 ICT 2021
	 */
	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @mbg.generated  Fri Jul 30 22:07:16 ICT 2021
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
	 * @param password  the value for user.password
	 * @mbg.generated  Fri Jul 30 22:07:16 ICT 2021
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.status
	 * @return  the value of user.status
	 * @mbg.generated  Fri Jul 30 22:07:16 ICT 2021
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.status
	 * @param status  the value for user.status
	 * @mbg.generated  Fri Jul 30 22:07:16 ICT 2021
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.username
	 * @return  the value of user.username
	 * @mbg.generated  Fri Jul 30 22:07:16 ICT 2021
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.username
	 * @param username  the value for user.username
	 * @mbg.generated  Fri Jul 30 22:07:16 ICT 2021
	 */
	public void setUsername(String username) {
		this.username = username;
	}
}