package com.web.spring.mapper;

import com.web.spring.model.User;
import com.web.spring.model.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.web.spring.model.UserWithBLOBs;

public interface UserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Fri Jul 30 22:07:16 ICT 2021
	 */
	long countByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Fri Jul 30 22:07:16 ICT 2021
	 */
	int deleteByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Fri Jul 30 22:07:16 ICT 2021
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Fri Jul 30 22:07:16 ICT 2021
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Fri Jul 30 22:07:16 ICT 2021
	 */
	List<User> selectByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Fri Jul 30 22:07:16 ICT 2021
	 */
	int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Fri Jul 30 22:07:16 ICT 2021
	 */
	int updateByExample(@Param("record") User record, @Param("example") UserExample example);
}